# -*- coding: utf-8 -*-
"""Day2a

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aDSUg4W4auXYwWB7Eto7zOkqv6DPzZwI
"""

import pandas as pd

url = "https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv"
df = pd.read_csv(url)

df.head()

df.select_dtypes(include="number").columns

df.describe()

df.select_dtypes(include="number").var().sort_values(ascending=False)

stats = df.select_dtypes(include="number").describe().T
stats["cv"] = stats["std"] / stats["mean"]
stats[["mean", "std", "cv"]].sort_values("cv", ascending=False)

"""Should memorise:
df.head()
df.tail()
df.shape
df.info()
df.describe()
df.columns
df.dtypes

Column & Row Selection
df["col"]
df[["col1", "col2"]]
df.loc[rows, cols]
df.iloc[rows, cols]
df.select_dtypes(...)

Filtering
df[df["latency_ms"] > 500]
df[(df["status"] == "FAIL") & (df["endpoint"] == "/login")]

Aggregation & Grouping
df.groupby("endpoint")["latency_ms"].mean()
df.groupby("endpoint").agg({
    "latency_ms": "mean",
    "status": "count"
})
"""