# -*- coding: utf-8 -*-
"""Day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wzb1o6JmB8CCwODzbNivNX8dT5ZYS0HV
"""

import pandas as pd

logs = [
    {"endpoint": "/login", "latency_ms": 120, "status": "SUCCESS"},
    {"endpoint": "/login", "latency_ms": 980, "status": "FAIL"},
    {"endpoint": "/order", "latency_ms": 450, "status": "SUCCESS"},
    {"endpoint": "/order", "latency_ms": 780, "status": "SUCCESS"},
    {"endpoint": "/payment", "latency_ms": 1500, "status": "FAIL"},
    {"endpoint": "/payment", "latency_ms": 1300, "status": "FAIL"}
]

df = pd.DataFrame(logs)
df

"""Raw latency is noisy.
Binary signals are stable & interpretable.
"""

SLO_MS = 500
df["is_slow"] = df["latency_ms"] > SLO_MS
df

df["is_error"] = df["status"] == "FAIL"
df

endpoint_features = (
    df.groupby("endpoint")
      .agg(
          avg_latency=("latency_ms", "mean"),
          p95_latency=("latency_ms", lambda x: x.quantile(0.95)),
          error_rate=("is_error", "mean"),
          slow_rate=("is_slow", "mean"),
          request_count=("endpoint", "count")
      )
)

endpoint_features

endpoint_features["risk_score"] = (
    endpoint_features["error_rate"] * 0.6 +
    endpoint_features["slow_rate"] * 0.4
)

endpoint_features.sort_values("risk_score", ascending=False)

df_encoded = pd.get_dummies(df, columns=["endpoint"], drop_first=True)
df_encoded

df["latency_normalized"] = (
    df["latency_ms"] / df["latency_ms"].max()
)

df[["latency_ms", "latency_normalized"]]

feature_columns = [
    "latency_ms",
    "is_slow",
    "is_error"
]

X = df[feature_columns]
X

endpoint_features.to_csv("day3_endpoint_features.csv")
df_encoded.to_csv("day3_request_features.csv", index=False)