# -*- coding: utf-8 -*-
"""Python_for_Backend_Engineers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158GHnWM8LTVnYT9bcoGh9dawPC0-zETo

# Day 1: Python for Backend Engineers

Goal:
- Use Python as a backend utility language
- Parse APIs
- Transform data
- Analyze logs
"""

def normalize_user(user):
    return {
        "name": user.get("name", "").strip().title(),
        "age": user.get("age", 0),
        "active": user.get("status") == "ACTIVE"
    }

user = {"name": " aritra ", "age": 36, "status": "ACTIVE"}
print(normalize_user(user))

"""Simulated API Response Parsing"""

api_response = {
    "data": [
        {"id": 1, "latency_ms": 120, "status": "SUCCESS"},
        {"id": 2, "latency_ms": 980, "status": "FAIL"},
        {"id": 3, "latency_ms": 450, "status": "SUCCESS"}
    ]
}

slow_requests = [
    req for req in api_response["data"]
    if req["latency_ms"] > 500
]

slow_requests

"""Simple Metrics (Very Interview-Relevant)"""

latencies = [req["latency_ms"] for req in api_response["data"]]

avg_latency = sum(latencies) / len(latencies)
max_latency = max(latencies)

print(sum(latencies))
print(len(latencies))

avg_latency, max_latency

"""Error Rate Calculation"""

total = len(api_response["data"])
failures = len([r for r in api_response["data"] if r["status"] == "FAIL"])

error_rate = failures / total
error_rate

"""Writing Clean, Reusable Functions"""

def calculate_error_rate(records):
    if not records:
        return 0
    failures = sum(1 for r in records if r["status"] == "FAIL")
    return failures / len(records)

calculate_error_rate(api_response["data"])

"""Save Output for GitHub"""

# Save a small report
with open("day1_report.txt", "w") as f:
    f.write(f"Avg latency: {avg_latency}\n")
    f.write(f"Max latency: {max_latency}\n")
    f.write(f"Error rate: {error_rate}\n")

"""What I learned:
- Python is excellent for backend utilities
- Perfect for data analysis & AI glue code
- Complements Java services well
"""